### ISSUE TITLE
Acceptance rate on the device doesn't match on the pool dashboard?

### ISSUE THREAD

**Issue by sahil912** [Mrtops/iOS-Miner#3]
Hi,

I am mining using this library @ the rate of 100 H/s, getting some 164 shares accepted on the device in the span of 6-8 hours. On checking the Acceptance rate on mining pool [dashboard](https://xmr.nanopool.org/account/44Ji5w8aEHcPaGiFQnfmN7DQAj8Wrf5qHaLuVr6Nd27xKuPHa4PFDdfXfthUGUcgmk6caJBB7kFjJ7mtmhTGRNWG2fqRxzY), it doesn't show the same accepted shares?  
So if the accepted shares on the device shows 164/164, shouldn't dashboard also show the same number of shares or is there a different equation to it?
Hoping to hear from you @ the earliest.

Thanks

**Comment by Mrtops** [comment]
There may be some variation but this is interesting because there is much variation. I have personally never looked into this and I have gotten about 100-200 shares in about 12 hours so I will look into this to see if it is just your pool or an app issue but your earnings look about what they should for a phone so you can keep using it but it may not be accurate for shares I will let you know what I find

**Comment by Mrtops** [comment]
Ok so what I believe is happening is it is displaying how many groups of hashes it has successfully submitted. So it is not the number of shares submitted. This grouping of submitted hashes is caused by a throttle that was intentionally put on submit upstream work as is outlined in the README.md

**Comment by sahil912** [comment]
So Do we have any way to know the exact shares that were accepted on the pool?

**Comment by Mrtops** [comment]
Check your pools Dashboard it should say but as of right now there is no direct way to in the app. Could be a possible future feature though
